#!/bin/bash
# Dependency Graph Visualizer
# Generates a Mermaid dependency graph from backlog items.
# Output: stdout (paste into a .md file or view at mermaid.live)
# Run from project root.

BACKLOG_DIR="${1:-project-management/backlog}"
USER_STORIES_DIR="${BACKLOG_DIR}/user-stories"
DEFECTS_DIR="${BACKLOG_DIR}/defects"

echo "%% Dependency Graph - Auto-generated by visualize-dependencies.sh"
echo "%% Run: ./project-management/scripts/visualize-dependencies.sh"
echo ""
echo "flowchart TD"
echo ""

# Extract dependencies from user stories and defects
for dir in "$USER_STORIES_DIR" "$DEFECTS_DIR"; do
    [ ! -d "$dir" ] && continue
    for f in "$dir"/*.md; do
        [ ! -f "$f" ] && continue
        id=$(basename "$f" .md | grep -oE '^(US|DEF)-[0-9]+')
        [ -z "$id" ] && continue
        title=$(grep -m1 '^# ' "$f" 2>/dev/null | sed -E 's/^# .*(US|DEF|TD)-[0-9]+ - //' | tr -d '[]' | head -c 35)
        node_id=$(echo "$id" | tr '-' '_')
        echo "    $node_id[\"$id: ${title:-...}\"]"
    done
done

# Output dependency edges
for dir in "$USER_STORIES_DIR" "$DEFECTS_DIR"; do
    [ ! -d "$dir" ] && continue
    for f in "$dir"/*.md; do
        [ ! -f "$f" ] && continue
        id=$(basename "$f" .md | grep -oE '^(US|DEF)-[0-9]+')
        [ -z "$id" ] && continue
        node_id=$(echo "$id" | tr '-' '_')
        deps=$(grep -A 20 '## Dependencies' "$f" 2>/dev/null | grep -oE '(US|DEF|TD)-[0-9]+' || true)
        for dep in $deps; do
            dep_node=$(echo "$dep" | tr '-' '_')
            echo "    $dep_node --> $node_id"
        done
    done
done

echo ""
echo "%% Paste this into a .md file or https://mermaid.live to view"
